version: '3'
services:
  snowdepth:
    image: 'diwise/api-snowdepth:latest'
    build:
      context: ..
      dockerfile: ./deployments/Dockerfile
    restart: always
    depends_on:
      - rabbitmq
      - postgresdb
    links:
      - rabbitmq
      - postgresdb
    environment:
      SNOWDEPTH_DB_HOST: 'postgresdb'
      SNOWDEPTH_DB_USER: 'testuser'
      SNOWDEPTH_DB_NAME: 'snowdepth'
      SNOWDEPTH_DB_PASSWORD: 'testpass'
      SNOWDEPTH_DB_SSLMODE: 'disable'
      SNOWDEPTH_API_PORT: '8282'
      RABBITMQ_HOST: 'rabbitmq'
      
    ports:
      - '8282:8282'


  deviceregistry:
    image: 'diwise/iot-device-registry:latest'
    restart: always
    environment:
      SERVICE_PORT: '8990'

    ports:
      - '8990'


  federation:
    build:
      context: ..
      dockerfile: ./test/federation/federation-dockerfile
    restart: always
    environment:
      API_GQL_FEDERATION_PORT: '8989'
      API_GQL_FEDERATION_SVCS: 'snowdepth:8282,deviceregistry:8990'
    ports:
      - '8989:8989'


  ingress:
    image: 'diwise/ingress-mqtt:latest'
    restart: always
    depends_on:
      - snowdepth
    links:
      - rabbitmq
    environment:
      MQTT_HOST: $MQTT_HOST
      MQTT_PORT: $MQTT_PORT
      MQTT_TOPIC: $MQTT_TOPIC
      MQTT_USER: $MQTT_USER
      MQTT_PASSWORD: $MQTT_PASSWORD
      RABBITMQ_HOST: 'rabbitmq'
      RABBITMQ_USER: 'user'
      RABBITMQ_PASSWORD: 'bitnami'
    
  
  postgresdb:
    image: 'diwise/testdb-postgres:latest'
    build:
      context: ..
      dockerfile: ./test/database/testdb-dockerfile
    restart: always
    environment:
      POSTGRES_DB: 'snowdepth'
      POSTGRES_USER: 'testuser'
      POSTGRES_PASSWORD: 'testpass'
    ports:
      - '5432'


  rabbitmq:
    image: 'bitnami/rabbitmq:3.8'
    ports:
      - '4369'
      - '5672'
      - '25672'
      - '15672'
    volumes:
      - 'rabbitmq_data:/bitnami'


volumes:
  rabbitmq_data:
    driver: local
