version: '3'
services:
  snowdepth:
    image: 'diwise/api-snowdepth:latest'
    build:
      context: ..
      dockerfile: ./deployments/Dockerfile
    restart: always
    depends_on:
      - rabbitmq
      - postgresdb
    links:
      - rabbitmq
      - postgresdb
    environment:
      SNOWDEPTH_DB_HOST: 'postgresdb'
      SNOWDEPTH_DB_USER: 'testuser'
      SNOWDEPTH_DB_NAME: 'snowdepth'
      SNOWDEPTH_DB_PASSWORD: 'testpass'
      SNOWDEPTH_DB_SSLMODE: 'disable'
      SNOWDEPTH_API_PORT: '8282'
      RABBITMQ_HOST: 'rabbitmq'
      
    ports:
      - '8282:8282'


  deviceregistry:
    image: 'ghcr.io/diwise/iot-device-registry@sha256:26466ab75b98586aeeaadae11d55b0b969463d76e5e5c5bf705d097f4c43301e'
    restart: always
    environment:
      DIWISE_SQLDB_HOST: 'postgresdb'
      DIWISE_SQLDB_USER: 'testuser'
      DIWISE_SQLDB_NAME: 'snowdepth'
      DIWISE_SQLDB_PASSWORD: 'testpass'
      DIWISE_SQLDB_SSLMODE: 'disable'
      RABBITMQ_HOST: 'rabbitmq'
      SERVICE_PORT: '8990'

    ports:
      - '8990'


  federation:
    image: 'ghcr.io/diwise/api-graphql:prod-10f7bb569256a100d2d6df73c12ddc31c30f14c5'
    restart: always
    environment:
      API_GQL_FEDERATION_PORT: '8989'
      API_GQL_FEDERATION_SVCS: 'snowdepth:8282,deviceregistry:8990'
    ports:
      - '8989:8989'


  ingress:
    image: 'ghcr.io/diwise/ingress-mqtt@sha256:b1c717c5a9c3863c267c45b56fe57ffd6a5e056070cd594d7744790f1c1fa7e3'
    restart: always
    depends_on:
      - snowdepth
    links:
      - rabbitmq
    environment:
      MQTT_HOST: $MQTT_HOST
      MQTT_PORT: $MQTT_PORT
      MQTT_TOPIC: $MQTT_TOPIC
      MQTT_USER: $MQTT_USER
      MQTT_PASSWORD: $MQTT_PASSWORD
      DIWISE_CONTEXT_BROKER_URL: 'http://snowdepth:8282'
      RABBITMQ_HOST: 'rabbitmq'
      RABBITMQ_USER: 'user'
      RABBITMQ_PASSWORD: 'bitnami'
    
  
  postgresdb:
    image: 'ghcr.io/diwise/test-db-postgresql:prod-824e7cffd65dd3766c88441a48cffd5b2acd55f2'
    restart: always
    environment:
      POSTGRES_DB: 'snowdepth'
      POSTGRES_USER: 'testuser'
      POSTGRES_PASSWORD: 'testpass'
    ports:
      - '5432'


  rabbitmq:
    image: 'bitnami/rabbitmq:3.8'
    ports:
      - '4369'
      - '5672'
      - '25672'
      - '15672'
    volumes:
      - 'rabbitmq_data:/bitnami'


volumes:
  rabbitmq_data:
    driver: local
